SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `patryks-flags-api`
--

-- --------------------------------------------------------

--
-- Table structure for table `flags`
--

CREATE TABLE `flags` (
  `Country Name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Country Code` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Flag` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `flags`
--

INSERT INTO `flags` (`Country Name`, `Country Code`, `Flag`) VALUES
('Afghanistan', 'AF', NULL),
('Albania', 'AL', NULL),
('Algeria', 'DZ', NULL),
('Andorra', 'AD', NULL),
('Angola', 'AO', NULL),
('Antigua and Barbuda', 'AG', NULL),
('Argentina', 'AR', NULL),
('Armenia', 'AM', NULL),
('Australia', 'AU', NULL),
('Austria', 'AT', NULL),
('Azerbaijan', 'AZ', NULL),
('Bahamas', 'BS', NULL),
('Bahrain', 'BH', NULL),
('Bangladesh', 'BD', NULL),
('Barbados', 'BB', NULL),
('Belarus', 'BY', NULL),
('Belgium', 'BE', NULL),
('Belize', 'BZ', NULL),
('Benin', 'BJ', NULL),
('Bhutan', 'BT', NULL),
('Bolivia', 'BO', NULL),
('Bosnia and Herzegovina', 'BA', NULL),
('Botswana', 'BW', NULL),
('Brazil', 'BR', NULL),
('Brunei', 'BN', NULL),
('Bulgaria', 'BG', NULL),
('Burkina Faso', 'BF', NULL),
('Burundi', 'BI', NULL),
('Cabo Verde', 'CV', NULL),
('Cambodia', 'KH', NULL),
('Cameroon', 'CM', NULL),
('Canada', 'CA', NULL),
('Central African Republic', 'CF', NULL),
('Chad', 'TD', NULL),
('Chile', 'CL', NULL),
('China', 'CN', NULL),
('Colombia', 'CO', NULL),
('Comoros', 'KM', NULL),
('Congo (Congo-Brazzaville)', 'CG', NULL),
('Costa Rica', 'CR', NULL),
('Croatia', 'HR', NULL),
('Cuba', 'CU', NULL),
('Cyprus', 'CY', NULL),
('Czechia', 'CZ', NULL),
('Democratic Republic of the Congo', 'CD', NULL),
('Denmark', 'DK', NULL),
('Djibouti', 'DJ', NULL),
('Dominica', 'DM', NULL),
('Dominican Republic', 'DO', NULL),
('Ecuador', 'EC', NULL),
('Egypt', 'EG', NULL),
('El Salvador', 'SV', NULL),
('Equatorial Guinea', 'GQ', NULL),
('Eritrea', 'ER', NULL),
('Estonia', 'EE', NULL),
('Eswatini', 'SZ', NULL),
('Ethiopia', 'ET', NULL),
('Fiji', 'FJ', NULL),
('Finland', 'FI', NULL),
('France', 'FR', NULL),
('Gabon', 'GA', NULL),
('Gambia', 'GM', NULL),
('Georgia', 'GE', NULL),
('Germany', 'DE', NULL),
('Ghana', 'GH', NULL),
('Greece', 'GR', NULL),
('Grenada', 'GD', NULL),
('Guatemala', 'GT', NULL),
('Guinea', 'GN', NULL),
('Guinea-Bissau', 'GW', NULL),
('Guyana', 'GY', NULL),
('Haiti', 'HT', NULL),
('Honduras', 'HN', NULL),
('Hungary', 'HU', NULL),
('Iceland', 'IS', NULL),
('India', 'IN', NULL),
('Indonesia', 'ID', NULL),
('Iran', 'IR', NULL),
('Iraq', 'IQ', NULL),
('Ireland', 'IE', NULL),
('Israel', 'IL', NULL),
('Italy', 'IT', NULL),
('Jamaica', 'JM', NULL),
('Japan', 'JP', NULL),
('Jordan', 'JO', NULL),
('Kazakhstan', 'KZ', NULL),
('Kenya', 'KE', NULL),
('Kiribati', 'KI', NULL),
('Kuwait', 'KW', NULL),
('Kyrgyzstan', 'KG', NULL),
('Laos', 'LA', NULL),
('Latvia', 'LV', NULL),
('Lebanon', 'LB', NULL),
('Lesotho', 'LS', NULL),
('Liberia', 'LR', NULL),
('Libya', 'LY', NULL),
('Liechtenstein', 'LI', NULL),
('Lithuania', 'LT', NULL),
('Luxembourg', 'LU', NULL),
('Madagascar', 'MG', NULL),
('Malawi', 'MW', NULL),
('Malaysia', 'MY', NULL),
('Maldives', 'MV', NULL),
('Mali', 'ML', NULL),
('Malta', 'MT', NULL),
('Marshall Islands', 'MH', NULL),
('Mauritania', 'MR', NULL),
('Mauritius', 'MU', NULL),
('Mexico', 'MX', NULL),
('Micronesia', 'FM', NULL),
('Moldova', 'MD', NULL),
('Monaco', 'MC', NULL),
('Mongolia', 'MN', NULL),
('Montenegro', 'ME', NULL),
('Morocco', 'MA', NULL),
('Mozambique', 'MZ', NULL),
('Myanmar', 'MM', NULL),
('Namibia', 'NA', NULL),
('Nauru', 'NR', NULL),
('Nepal', 'NP', NULL),
('Netherlands', 'NL', NULL),
('New Zealand', 'NZ', NULL),
('Nicaragua', 'NI', NULL),
('Niger', 'NE', NULL),
('Nigeria', 'NG', NULL),
('North Korea', 'KP', NULL),
('North Macedonia', 'MK', NULL),
('Norway', 'NO', NULL),
('Oman', 'OM', NULL),
('Pakistan', 'PK', NULL),
('Palau', 'PW', NULL),
('Palestine', 'PS', NULL),
('Panama', 'PA', NULL),
('Papua New Guinea', 'PG', NULL),
('Paraguay', 'PY', NULL),
('Peru', 'PE', NULL),
('Philippines', 'PH', NULL),
('Poland', 'PL', NULL),
('Portugal', 'PT', NULL),
('Qatar', 'QA', NULL),
('Romania', 'RO', NULL),
('Russia', 'RU', NULL),
('Rwanda', 'RW', NULL),
('Saint Kitts and Nevis', 'KN', NULL),
('Saint Lucia', 'LC', NULL),
('Saint Vincent and the Grenadines', 'VC', NULL),
('Samoa', 'WS', NULL),
('San Marino', 'SM', NULL),
('Sao Tome and Principe', 'ST', NULL),
('Saudi Arabia', 'SA', NULL),
('Senegal', 'SN', NULL),
('Serbia', 'RS', NULL),
('Seychelles', 'SC', NULL),
('Sierra Leone', 'SL', NULL),
('Singapore', 'SG', NULL),
('Slovakia', 'SK', NULL),
('Slovenia', 'SI', NULL),
('Solomon Islands', 'SB', NULL),
('Somalia', 'SO', NULL),
('South Africa', 'ZA', NULL),
('South Korea', 'KR', NULL),
('South Sudan', 'SS', NULL),
('Spain', 'ES', NULL),
('Sri Lanka', 'LK', NULL),
('Sudan', 'SD', NULL),
('Suriname', 'SR', NULL),
('Sweden', 'SE', NULL),
('Switzerland', 'CH', NULL),
('Syria', 'SY', NULL),
('Tajikistan', 'TJ', NULL),
('Tanzania', 'TZ', NULL),
('Thailand', 'TH', NULL),
('Timor-Leste', 'TL', NULL),
('Togo', 'TG', NULL),
('Tonga', 'TO', NULL),
('Trinidad and Tobago', 'TT', NULL),
('Tunisia', 'TN', NULL),
('Turkey', 'TR', NULL),
('Turkmenistan', 'TM', NULL),
('Tuvalu', 'TV', NULL),
('Uganda', 'UG', NULL),
('Ukraine', 'UA', NULL),
('United Arab Emirates', 'AE', NULL),
('United Kingdom', 'GB', NULL),
('United States', 'US', NULL),
('Uruguay', 'UY', NULL),
('Uzbekistan', 'UZ', NULL),
('Vanuatu', 'VU', NULL),
('Venezuela', 'VE', NULL),
('Vietnam', 'VN', NULL),
('Yemen', 'YE', NULL),
('Zambia', 'ZM', NULL),
('Zimbabwe', 'ZW', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `flags`
--
ALTER TABLE `flags`
  ADD UNIQUE KEY `Country Name` (`Country Name`,`Country Code`),
  ADD UNIQUE KEY `Flag` (`Flag`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
