<?php

/**
 * Database `patryks-flags-api`
 */

/* `patryks-flags-api`.`flags` */
$flags = array(
  array('Country Name' => 'Afghanistan','Country Code' => 'AF','Flag' => NULL),
  array('Country Name' => 'Albania','Country Code' => 'AL','Flag' => NULL),
  array('Country Name' => 'Algeria','Country Code' => 'DZ','Flag' => NULL),
  array('Country Name' => 'Andorra','Country Code' => 'AD','Flag' => NULL),
  array('Country Name' => 'Angola','Country Code' => 'AO','Flag' => NULL),
  array('Country Name' => 'Antigua and Barbuda','Country Code' => 'AG','Flag' => NULL),
  array('Country Name' => 'Argentina','Country Code' => 'AR','Flag' => NULL),
  array('Country Name' => 'Armenia','Country Code' => 'AM','Flag' => NULL),
  array('Country Name' => 'Australia','Country Code' => 'AU','Flag' => NULL),
  array('Country Name' => 'Austria','Country Code' => 'AT','Flag' => NULL),
  array('Country Name' => 'Azerbaijan','Country Code' => 'AZ','Flag' => NULL),
  array('Country Name' => 'Bahamas','Country Code' => 'BS','Flag' => NULL),
  array('Country Name' => 'Bahrain','Country Code' => 'BH','Flag' => NULL),
  array('Country Name' => 'Bangladesh','Country Code' => 'BD','Flag' => NULL),
  array('Country Name' => 'Barbados','Country Code' => 'BB','Flag' => NULL),
  array('Country Name' => 'Belarus','Country Code' => 'BY','Flag' => NULL),
  array('Country Name' => 'Belgium','Country Code' => 'BE','Flag' => NULL),
  array('Country Name' => 'Belize','Country Code' => 'BZ','Flag' => NULL),
  array('Country Name' => 'Benin','Country Code' => 'BJ','Flag' => NULL),
  array('Country Name' => 'Bhutan','Country Code' => 'BT','Flag' => NULL),
  array('Country Name' => 'Bolivia','Country Code' => 'BO','Flag' => NULL),
  array('Country Name' => 'Bosnia and Herzegovina','Country Code' => 'BA','Flag' => NULL),
  array('Country Name' => 'Botswana','Country Code' => 'BW','Flag' => NULL),
  array('Country Name' => 'Brazil','Country Code' => 'BR','Flag' => NULL),
  array('Country Name' => 'Brunei','Country Code' => 'BN','Flag' => NULL),
  array('Country Name' => 'Bulgaria','Country Code' => 'BG','Flag' => NULL),
  array('Country Name' => 'Burkina Faso','Country Code' => 'BF','Flag' => NULL),
  array('Country Name' => 'Burundi','Country Code' => 'BI','Flag' => NULL),
  array('Country Name' => 'Cabo Verde','Country Code' => 'CV','Flag' => NULL),
  array('Country Name' => 'Cambodia','Country Code' => 'KH','Flag' => NULL),
  array('Country Name' => 'Cameroon','Country Code' => 'CM','Flag' => NULL),
  array('Country Name' => 'Canada','Country Code' => 'CA','Flag' => NULL),
  array('Country Name' => 'Central African Republic','Country Code' => 'CF','Flag' => NULL),
  array('Country Name' => 'Chad','Country Code' => 'TD','Flag' => NULL),
  array('Country Name' => 'Chile','Country Code' => 'CL','Flag' => NULL),
  array('Country Name' => 'China','Country Code' => 'CN','Flag' => NULL),
  array('Country Name' => 'Colombia','Country Code' => 'CO','Flag' => NULL),
  array('Country Name' => 'Comoros','Country Code' => 'KM','Flag' => NULL),
  array('Country Name' => 'Congo (Congo-Brazzaville)','Country Code' => 'CG','Flag' => NULL),
  array('Country Name' => 'Costa Rica','Country Code' => 'CR','Flag' => NULL),
  array('Country Name' => 'Croatia','Country Code' => 'HR','Flag' => NULL),
  array('Country Name' => 'Cuba','Country Code' => 'CU','Flag' => NULL),
  array('Country Name' => 'Cyprus','Country Code' => 'CY','Flag' => NULL),
  array('Country Name' => 'Czechia','Country Code' => 'CZ','Flag' => NULL),
  array('Country Name' => 'Democratic Republic of the Congo','Country Code' => 'CD','Flag' => NULL),
  array('Country Name' => 'Denmark','Country Code' => 'DK','Flag' => NULL),
  array('Country Name' => 'Djibouti','Country Code' => 'DJ','Flag' => NULL),
  array('Country Name' => 'Dominica','Country Code' => 'DM','Flag' => NULL),
  array('Country Name' => 'Dominican Republic','Country Code' => 'DO','Flag' => NULL),
  array('Country Name' => 'Ecuador','Country Code' => 'EC','Flag' => NULL),
  array('Country Name' => 'Egypt','Country Code' => 'EG','Flag' => NULL),
  array('Country Name' => 'El Salvador','Country Code' => 'SV','Flag' => NULL),
  array('Country Name' => 'Equatorial Guinea','Country Code' => 'GQ','Flag' => NULL),
  array('Country Name' => 'Eritrea','Country Code' => 'ER','Flag' => NULL),
  array('Country Name' => 'Estonia','Country Code' => 'EE','Flag' => NULL),
  array('Country Name' => 'Eswatini','Country Code' => 'SZ','Flag' => NULL),
  array('Country Name' => 'Ethiopia','Country Code' => 'ET','Flag' => NULL),
  array('Country Name' => 'Fiji','Country Code' => 'FJ','Flag' => NULL),
  array('Country Name' => 'Finland','Country Code' => 'FI','Flag' => NULL),
  array('Country Name' => 'France','Country Code' => 'FR','Flag' => NULL),
  array('Country Name' => 'Gabon','Country Code' => 'GA','Flag' => NULL),
  array('Country Name' => 'Gambia','Country Code' => 'GM','Flag' => NULL),
  array('Country Name' => 'Georgia','Country Code' => 'GE','Flag' => NULL),
  array('Country Name' => 'Germany','Country Code' => 'DE','Flag' => NULL),
  array('Country Name' => 'Ghana','Country Code' => 'GH','Flag' => NULL),
  array('Country Name' => 'Greece','Country Code' => 'GR','Flag' => NULL),
  array('Country Name' => 'Grenada','Country Code' => 'GD','Flag' => NULL),
  array('Country Name' => 'Guatemala','Country Code' => 'GT','Flag' => NULL),
  array('Country Name' => 'Guinea','Country Code' => 'GN','Flag' => NULL),
  array('Country Name' => 'Guinea-Bissau','Country Code' => 'GW','Flag' => NULL),
  array('Country Name' => 'Guyana','Country Code' => 'GY','Flag' => NULL),
  array('Country Name' => 'Haiti','Country Code' => 'HT','Flag' => NULL),
  array('Country Name' => 'Honduras','Country Code' => 'HN','Flag' => NULL),
  array('Country Name' => 'Hungary','Country Code' => 'HU','Flag' => NULL),
  array('Country Name' => 'Iceland','Country Code' => 'IS','Flag' => NULL),
  array('Country Name' => 'India','Country Code' => 'IN','Flag' => NULL),
  array('Country Name' => 'Indonesia','Country Code' => 'ID','Flag' => NULL),
  array('Country Name' => 'Iran','Country Code' => 'IR','Flag' => NULL),
  array('Country Name' => 'Iraq','Country Code' => 'IQ','Flag' => NULL),
  array('Country Name' => 'Ireland','Country Code' => 'IE','Flag' => NULL),
  array('Country Name' => 'Israel','Country Code' => 'IL','Flag' => NULL),
  array('Country Name' => 'Italy','Country Code' => 'IT','Flag' => NULL),
  array('Country Name' => 'Jamaica','Country Code' => 'JM','Flag' => NULL),
  array('Country Name' => 'Japan','Country Code' => 'JP','Flag' => NULL),
  array('Country Name' => 'Jordan','Country Code' => 'JO','Flag' => NULL),
  array('Country Name' => 'Kazakhstan','Country Code' => 'KZ','Flag' => NULL),
  array('Country Name' => 'Kenya','Country Code' => 'KE','Flag' => NULL),
  array('Country Name' => 'Kiribati','Country Code' => 'KI','Flag' => NULL),
  array('Country Name' => 'Kuwait','Country Code' => 'KW','Flag' => NULL),
  array('Country Name' => 'Kyrgyzstan','Country Code' => 'KG','Flag' => NULL),
  array('Country Name' => 'Laos','Country Code' => 'LA','Flag' => NULL),
  array('Country Name' => 'Latvia','Country Code' => 'LV','Flag' => NULL),
  array('Country Name' => 'Lebanon','Country Code' => 'LB','Flag' => NULL),
  array('Country Name' => 'Lesotho','Country Code' => 'LS','Flag' => NULL),
  array('Country Name' => 'Liberia','Country Code' => 'LR','Flag' => NULL),
  array('Country Name' => 'Libya','Country Code' => 'LY','Flag' => NULL),
  array('Country Name' => 'Liechtenstein','Country Code' => 'LI','Flag' => NULL),
  array('Country Name' => 'Lithuania','Country Code' => 'LT','Flag' => NULL),
  array('Country Name' => 'Luxembourg','Country Code' => 'LU','Flag' => NULL),
  array('Country Name' => 'Madagascar','Country Code' => 'MG','Flag' => NULL),
  array('Country Name' => 'Malawi','Country Code' => 'MW','Flag' => NULL),
  array('Country Name' => 'Malaysia','Country Code' => 'MY','Flag' => NULL),
  array('Country Name' => 'Maldives','Country Code' => 'MV','Flag' => NULL),
  array('Country Name' => 'Mali','Country Code' => 'ML','Flag' => NULL),
  array('Country Name' => 'Malta','Country Code' => 'MT','Flag' => NULL),
  array('Country Name' => 'Marshall Islands','Country Code' => 'MH','Flag' => NULL),
  array('Country Name' => 'Mauritania','Country Code' => 'MR','Flag' => NULL),
  array('Country Name' => 'Mauritius','Country Code' => 'MU','Flag' => NULL),
  array('Country Name' => 'Mexico','Country Code' => 'MX','Flag' => NULL),
  array('Country Name' => 'Micronesia','Country Code' => 'FM','Flag' => NULL),
  array('Country Name' => 'Moldova','Country Code' => 'MD','Flag' => NULL),
  array('Country Name' => 'Monaco','Country Code' => 'MC','Flag' => NULL),
  array('Country Name' => 'Mongolia','Country Code' => 'MN','Flag' => NULL),
  array('Country Name' => 'Montenegro','Country Code' => 'ME','Flag' => NULL),
  array('Country Name' => 'Morocco','Country Code' => 'MA','Flag' => NULL),
  array('Country Name' => 'Mozambique','Country Code' => 'MZ','Flag' => NULL),
  array('Country Name' => 'Myanmar','Country Code' => 'MM','Flag' => NULL),
  array('Country Name' => 'Namibia','Country Code' => 'NA','Flag' => NULL),
  array('Country Name' => 'Nauru','Country Code' => 'NR','Flag' => NULL),
  array('Country Name' => 'Nepal','Country Code' => 'NP','Flag' => NULL),
  array('Country Name' => 'Netherlands','Country Code' => 'NL','Flag' => NULL),
  array('Country Name' => 'New Zealand','Country Code' => 'NZ','Flag' => NULL),
  array('Country Name' => 'Nicaragua','Country Code' => 'NI','Flag' => NULL),
  array('Country Name' => 'Niger','Country Code' => 'NE','Flag' => NULL),
  array('Country Name' => 'Nigeria','Country Code' => 'NG','Flag' => NULL),
  array('Country Name' => 'North Korea','Country Code' => 'KP','Flag' => NULL),
  array('Country Name' => 'North Macedonia','Country Code' => 'MK','Flag' => NULL),
  array('Country Name' => 'Norway','Country Code' => 'NO','Flag' => NULL),
  array('Country Name' => 'Oman','Country Code' => 'OM','Flag' => NULL),
  array('Country Name' => 'Pakistan','Country Code' => 'PK','Flag' => NULL),
  array('Country Name' => 'Palau','Country Code' => 'PW','Flag' => NULL),
  array('Country Name' => 'Palestine','Country Code' => 'PS','Flag' => NULL),
  array('Country Name' => 'Panama','Country Code' => 'PA','Flag' => NULL),
  array('Country Name' => 'Papua New Guinea','Country Code' => 'PG','Flag' => NULL),
  array('Country Name' => 'Paraguay','Country Code' => 'PY','Flag' => NULL),
  array('Country Name' => 'Peru','Country Code' => 'PE','Flag' => NULL),
  array('Country Name' => 'Philippines','Country Code' => 'PH','Flag' => NULL),
  array('Country Name' => 'Poland','Country Code' => 'PL','Flag' => NULL),
  array('Country Name' => 'Portugal','Country Code' => 'PT','Flag' => NULL),
  array('Country Name' => 'Qatar','Country Code' => 'QA','Flag' => NULL),
  array('Country Name' => 'Romania','Country Code' => 'RO','Flag' => NULL),
  array('Country Name' => 'Russia','Country Code' => 'RU','Flag' => NULL),
  array('Country Name' => 'Rwanda','Country Code' => 'RW','Flag' => NULL),
  array('Country Name' => 'Saint Kitts and Nevis','Country Code' => 'KN','Flag' => NULL),
  array('Country Name' => 'Saint Lucia','Country Code' => 'LC','Flag' => NULL),
  array('Country Name' => 'Saint Vincent and the Grenadines','Country Code' => 'VC','Flag' => NULL),
  array('Country Name' => 'Samoa','Country Code' => 'WS','Flag' => NULL),
  array('Country Name' => 'San Marino','Country Code' => 'SM','Flag' => NULL),
  array('Country Name' => 'Sao Tome and Principe','Country Code' => 'ST','Flag' => NULL),
  array('Country Name' => 'Saudi Arabia','Country Code' => 'SA','Flag' => NULL),
  array('Country Name' => 'Senegal','Country Code' => 'SN','Flag' => NULL),
  array('Country Name' => 'Serbia','Country Code' => 'RS','Flag' => NULL),
  array('Country Name' => 'Seychelles','Country Code' => 'SC','Flag' => NULL),
  array('Country Name' => 'Sierra Leone','Country Code' => 'SL','Flag' => NULL),
  array('Country Name' => 'Singapore','Country Code' => 'SG','Flag' => NULL),
  array('Country Name' => 'Slovakia','Country Code' => 'SK','Flag' => NULL),
  array('Country Name' => 'Slovenia','Country Code' => 'SI','Flag' => NULL),
  array('Country Name' => 'Solomon Islands','Country Code' => 'SB','Flag' => NULL),
  array('Country Name' => 'Somalia','Country Code' => 'SO','Flag' => NULL),
  array('Country Name' => 'South Africa','Country Code' => 'ZA','Flag' => NULL),
  array('Country Name' => 'South Korea','Country Code' => 'KR','Flag' => NULL),
  array('Country Name' => 'South Sudan','Country Code' => 'SS','Flag' => NULL),
  array('Country Name' => 'Spain','Country Code' => 'ES','Flag' => NULL),
  array('Country Name' => 'Sri Lanka','Country Code' => 'LK','Flag' => NULL),
  array('Country Name' => 'Sudan','Country Code' => 'SD','Flag' => NULL),
  array('Country Name' => 'Suriname','Country Code' => 'SR','Flag' => NULL),
  array('Country Name' => 'Sweden','Country Code' => 'SE','Flag' => NULL),
  array('Country Name' => 'Switzerland','Country Code' => 'CH','Flag' => NULL),
  array('Country Name' => 'Syria','Country Code' => 'SY','Flag' => NULL),
  array('Country Name' => 'Tajikistan','Country Code' => 'TJ','Flag' => NULL),
  array('Country Name' => 'Tanzania','Country Code' => 'TZ','Flag' => NULL),
  array('Country Name' => 'Thailand','Country Code' => 'TH','Flag' => NULL),
  array('Country Name' => 'Timor-Leste','Country Code' => 'TL','Flag' => NULL),
  array('Country Name' => 'Togo','Country Code' => 'TG','Flag' => NULL),
  array('Country Name' => 'Tonga','Country Code' => 'TO','Flag' => NULL),
  array('Country Name' => 'Trinidad and Tobago','Country Code' => 'TT','Flag' => NULL),
  array('Country Name' => 'Tunisia','Country Code' => 'TN','Flag' => NULL),
  array('Country Name' => 'Turkey','Country Code' => 'TR','Flag' => NULL),
  array('Country Name' => 'Turkmenistan','Country Code' => 'TM','Flag' => NULL),
  array('Country Name' => 'Tuvalu','Country Code' => 'TV','Flag' => NULL),
  array('Country Name' => 'Uganda','Country Code' => 'UG','Flag' => NULL),
  array('Country Name' => 'Ukraine','Country Code' => 'UA','Flag' => NULL),
  array('Country Name' => 'United Arab Emirates','Country Code' => 'AE','Flag' => NULL),
  array('Country Name' => 'United Kingdom','Country Code' => 'GB','Flag' => NULL),
  array('Country Name' => 'United States','Country Code' => 'US','Flag' => NULL),
  array('Country Name' => 'Uruguay','Country Code' => 'UY','Flag' => NULL),
  array('Country Name' => 'Uzbekistan','Country Code' => 'UZ','Flag' => NULL),
  array('Country Name' => 'Vanuatu','Country Code' => 'VU','Flag' => NULL),
  array('Country Name' => 'Venezuela','Country Code' => 'VE','Flag' => NULL),
  array('Country Name' => 'Vietnam','Country Code' => 'VN','Flag' => NULL),
  array('Country Name' => 'Yemen','Country Code' => 'YE','Flag' => NULL),
  array('Country Name' => 'Zambia','Country Code' => 'ZM','Flag' => NULL),
  array('Country Name' => 'Zimbabwe','Country Code' => 'ZW','Flag' => NULL)
);
